### ISSUE TITLE
IMOS: KeyError in find_variables_from_attribute

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#29]
Running the IMOS checker on [this](http://thredds.aodn.org.au/thredds/catalog/IMOS/eMII/checker_test/ACORN/catalog.html?dataset=IMOS/eMII/checker_test/ACORN/IMOS_ACORN_V_20140406T003000Z_ROT_FV01_1-hour-avg.nc) file results in:

```
Traceback (most recent call last):
  File "/home/mhidas/code/compliance-checker/cchecker.py", line 27, in <module>
    sys.exit(main())
  File "/home/mhidas/code/compliance-checker/cchecker.py", line 21, in main
    args.criteria)
  File "/home/mhidas/code/compliance-checker/compliance_checker/runner.py", line 45, in run_checker
    score_groups = cs.run(ds, *checker_names)
  File "/home/mhidas/code/compliance-checker/compliance_checker/suite.py", line 85, in run
    checker.setup(dsp)
  File "/home/mhidas/code/compliance-checker/compliance_checker/imos/imos.py", line 46, in setup
    self._ancillary_variables = find_ancillary_variables(ds.dataset)
  File "/home/mhidas/code/compliance-checker/compliance_checker/imos/util.py", line 75, in find_ancillary_variables
    ancillary_variables.extend(find_variables_from_attribute(dataset, var, 'ancillary_variables'))
  File "/home/mhidas/code/compliance-checker/compliance_checker/imos/util.py", line 47, in find_variables_from_attribute
    variable = dataset.variables[variable_name]
KeyError: u'NOBS1,'
```

**Comment by mhidas** [comment]
@fxmzb123 Please have a look at this if you have time.

**Comment by mhidas** [comment]
@ggalibert In this case the exception is caused by the `ancillary_variables` attributes in the (ACORN) file (link above):

```
    UCUR:ancillary_variables = "NOBS1, NOBS2, UCUR_quality_control" ;
```

[CF](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#ancillary-data) says it should be a blank-separated list, not comma-separated.

The CF checker will also complain about this.

**Comment by lbesnard** [comment]
@mhidas this is a bug as well,the checker shouldn't fail

**Comment by ggalibert** [comment]
Created a pull request to fix that for newly created files in the future :

https://github.com/aodn/data-services/pull/179

Will need to fix historical files too.

**Comment by fxmzb123** [comment]
This has been fixed and created pull request #41

**Comment by ggalibert** [comment]
Historical ACORN hourly averaged products have been fixed accordingly.

**Comment by lbesnard** [comment]
works fine
